function gradf = user_fun_grad(in1)
%USER_FUN_GRAD
%    GRADF = USER_FUN_GRAD(IN1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    16-Dec-2023 12:53:22

gradf = [1.0;1.0;1.0;1.0];
end
