function f_user = user_fun(in1)
%USER_FUN
%    F_USER = USER_FUN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    16-Dec-2023 12:53:22

a1 = in1(1,:);
b1 = in1(2,:);
r1 = in1(3,:);
s1 = in1(4,:);
f_user = a1+b1+r1+s1;
end
