function hessf = user_fun_hess(in1)
%USER_FUN_HESS
%    HESSF = USER_FUN_HESS(IN1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    16-Dec-2023 12:53:22

hessf = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[4,4]);
end
